apiVersion: v1
kind: Service
metadata:
  name: adcpersistence
  labels:
    {{- include "frota-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: adcpersistence
    app.kubernetes.io/name: valecard-jboss
