{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "valecard-jboss.serviceAccountName" . }}
  labels:
{{ include "valecard-jboss.labels" . | nindent 4 }}
{{- end -}}
